"""empty message

Revision ID: 285f3b746b12
Revises: f98427601296
Create Date: 2023-08-25 11:49:15.991610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285f3b746b12'
down_revision = 'f98427601296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
